version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=cement
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=genericPassword
    volumes:
      - ./data/scripts:/docker-entrypoint-initdb.d
      - ./data/database:/data/db
    restart: on-failure
    ports:
      - "27017:27017"
    networks:
      - network
  web:
    container_name: cement
    restart: always
    environment:
      - TZ=America/Phoenix
    build: .
    ports:
      - "5555:5555"
    links:
      - mongo
    networks:
      - network
    volumes:
      - .:/code
    depends_on:
      - mongo
networks:
  network:
    driver: bridge